FROM amazon/aws-lambda-python:3.8

#RUN /var/lang/bin/python3.8 -m pip install --upgrade pip
#RUN /var/lang/bin/python3.8 -m pip install joblib
#RUN /var/lang/bin/python3.8 -m pip install scikit-learn
#RUN /var/lang/bin/python3.8 -m pip install awsiotsdk pandas

RUN yum install libglvnd-glx -y
RUN pip3 install --upgrade pip
RUN pip3 install scikit-build wheel gluoncv dlr

RUN python -m pip install dlr
RUN python -m pip install joblib awsiotsdk pandas

WORKDIR /var/task/dlr

COPY . .

#RUN pip install -r requirements.txt

ENTRYPOINT ["python3", "/var/task/dlr/main-test.py"]
